development: &dev
  database: pebbles_development
  adapter: postgresql
  username: rails
  password:
  min_messages: warning

staging:
  <<: *dev

production:
  <<: *dev

test: &TEST
  database: pebbles_test
  adapter: postgresql
  username: rails
  password:
  min_messages: warning

cucumber:
  <<: *TEST
