development:
  adapter: postgresql	
  database: pebbles_development
  username: jonathangreenberg
  password: tussy2
  host: 127.0.0.1

test:
  adapter: postgresql	
  database: pebbles_test
  username: jonathangreenberg
  password: tussy2
  host: 127.0.0.1


